"use client";

import { FormEvent, useEffect, useState } from "react";
import type { components } from "../../../../contracts/generated/api-types";
import { PageHeader, StatusMessage } from "../components/app-shell";
import { apiRequest, displayError } from "../lib/api";

type Schedule = components["schemas"]["ScheduleRead"];
type Preference = components["schemas"]["PreferenceRead"];
type Activity = components["schemas"]["ActivityRead"];

export default function SettingsPage() {
  const [schedule, setSchedule] = useState<Schedule | null>(null); const [preference, setPreference] = useState<Preference | null>(null); const [activity, setActivity] = useState<Activity[]>([]); const [message, setMessage] = useState("");
  useEffect(() => { void Promise.all([apiRequest<Schedule>("/settings/schedule").catch(() => null), apiRequest<Preference>("/notifications/preference").catch(() => null), apiRequest<Activity[]>("/account/activity").catch(() => [])]).then(([nextSchedule, nextPreference, nextActivity]) => { setSchedule(nextSchedule); setPreference(nextPreference); setActivity(nextActivity); }); }, []);
  async function saveSchedule(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); try { const result = await apiRequest<Schedule>("/settings/schedule", { method: "PUT", body: JSON.stringify({ timezone: data.get("timezone"), local_time: data.get("local_time"), enabled: data.get("enabled") === "on" }) }); setSchedule(result); setMessage("Daily schedule saved."); } catch (error) { setMessage(displayError(error)); } }
  async function savePreference(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); const channel = String(data.get("channel")); try { const result = await apiRequest<Preference>("/notifications/preference", { method: "PUT", body: JSON.stringify({ external_channel: channel, enabled: channel !== "NONE", destination: data.get("destination") || null }) }); setPreference(result); setMessage("Notification preference saved. DireHire will not fail over to another channel."); } catch (error) { setMessage(displayError(error)); } }
  return <><PageHeader eyebrow="Account defaults" title="Settings" /><StatusMessage>{message}</StatusMessage><div className="split-layout"><section className="surface"><h2>Daily Watch schedule</h2><form onSubmit={saveSchedule}><label>Timezone<input name="timezone" required defaultValue={schedule?.timezone ?? Intl.DateTimeFormat().resolvedOptions().timeZone} /></label><label>Local run time<input name="local_time" type="time" required defaultValue={schedule?.local_time?.slice(0, 5) ?? "08:00"} /></label><label className="check"><input name="enabled" type="checkbox" defaultChecked={schedule?.enabled ?? true} /> Run active Watches daily</label><button className="button primary">Save schedule</button></form>{schedule?.next_run_at && <p className="hint">Next run: {new Date(schedule.next_run_at).toLocaleString()}</p>}</section><section className="surface"><h2>Optional digest channel</h2><p className="supporting">In-app notifications remain the source of truth. Choose at most one external channel.</p><form onSubmit={savePreference}><label>Channel<select name="channel" defaultValue={preference?.external_channel ?? "NONE"}><option value="NONE">In-app only</option><option value="TELEGRAM">Telegram</option><option value="WHATSAPP">WhatsApp</option></select></label><label>Destination<input name="destination" placeholder={preference?.destination_hint ?? "Chat ID or phone number"} /></label><button className="button primary">Save preference</button></form></section></div><section className="surface"><h2>Account activity</h2><ul className="plain-list">{activity.map((item) => <li key={item.id}><span>{item.activity_type.replaceAll("_", " ")}</span><time dateTime={item.created_at}>{new Date(item.created_at).toLocaleString()}</time></li>)}</ul></section></>;
}
